### ISSUE TITLE
Sidebar label is always capitalized

### ISSUE THREAD

**Issue by B2o5T** [the-guild-org/the-guild-docs#366]
![image](https://user-images.githubusercontent.com/7361780/142627347-c5b81e12-f2c3-4dda-ac91-79b761a3cb85.png)
![image](https://user-images.githubusercontent.com/7361780/142627420-c97fe5d0-77e8-4606-90c2-7ae00259231f.png)

**Comment by PabloSzx** [comment]
This is not a bug, this just uses the CSS textTransform property, which can be completely customized:

for example:

```tsx
{isDocs ? (
        <DocsPage
          appProps={appProps}
          accentColor={accentColor}
          mdxRoutes={mdxRoutes}
          mdxNavigationProps={{
            summaryLabelProps() {
              return {
                textTransform: 'none',
              };
            },
          }}
        />
      ) : (
        <Component {...pageProps} />
      )}
```

which will do:

![image](https://user-images.githubusercontent.com/8672915/142676639-35a00db6-362d-4c30-bb6f-222c08f4c550.png)

This is a function because you can also do conditional styles:

```ts
 summaryLabelProps({
              depth,
              finalHref,
              isActive,
              isAnchor,
              isOpen
            }) {
              return {
                textTransform: 'none',
              };
            },
```
