### ISSUE TITLE
guild docs is incompatible with react 18

### ISSUE THREAD

**Issue by n1ru4l** [the-guild-org/the-guild-docs#580]

**Comment by B2o5T** [comment]
with react 17 or 18?

**Comment by n1ru4l** [comment]
18 my bad, I updated the title :D

**Comment by vicary** [comment]
@B2o5T I am working on https://github.com/gqty-dev/gqty/pull/772 and found that, despite this issue claims a finished migration, the peer dependency of `@theguild/components@^1.11.2` which should be upgraded to at least 2.0.0

**Comment by B2o5T** [comment]
@vicary `@theguild/components`@2.0.0 requires react 18

**Comment by vicary** [comment]
@B2o5T Oh I thought this issue is for React 18, I must have missed something.

I am upgrading to React 18 in https://github.com/gqty-dev/gqty/pull/772. When I upgrade `@guild-doc/client@^3.1.0` its peer dependency of `@theguild/components@^1.11.2` throws about React 18 being too new.

Is there a version of `@guild-doc/client` being compatible with React 18?

**Comment by B2o5T** [comment]
We no longer uses `@guild-doc/client`
see the example of website https://github.com/the-guild-org/the-guild-docs/tree/main/website

**Comment by vicary** [comment]
Thanks!
